version: "3.8"
services:
  app:
    build:
      context: app
      dockerfile: Dockerfile
    stdin_open: true 
    tty: true     
    environment:
      - CONFIG_FOLDER=/app/config/
      - CONFIG_FILE=/app/config/app_config.yaml
      - DEBUG_FOLDER=/app/debug
      - GST_DEBUG_DUMP_DOT_DIR=/app/debug/graphs
      - GST_DEBUG=2
      - LOGGING_LEVEL=DEBUG
    volumes:
      - ./app/:/app/
  prometheus:
    image: bitnami/prometheus:2-debian-10
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/opt/bitnami/prometheus/data
    ports:
      - 29800:9090
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    volumes:
      - ./grafana/etc/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/etc/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ./grafana/images/:/usr/share/grafana/public/img/
      - ./ds-analytics/images/:/usr/share/grafana/public/img/heatmap/
      - grafana-storage:/var/lib/grafana/
    links:
      - prometheus
volumes:
  prometheus_data:
    driver: local
  grafana-storage:
